config/routes.rb
Rails.application.routes.draw do
  resources :auto_parts

  get 'parts/by-make/:vehicle_make' => 'auto_parts#by_make'
  get 'parts/by-model/:vehicle_model' =>'auto_parts#by_model'
  get 'parts/by-price' => 'auto_parts#by_price'

end

app/models/auto_part.rb
class AutoPart < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/auto_parts_controller.rb
class AutoPartsController < ApplicationController
  before_action :set_auto_part, only: [:show, :edit, :update, :destroy]

  def by_price
    @auto_parts = AutoPart.all
    @order = AutoPart.all.order(:price)
  end

  def by_make
    @auto_parts = AutoPart.where(vehicle_make: params[:vehicle_make])

    if params[:vehicle_model]
      @auto_parts =@auto_parts.where(vehicle_model: params[:vehicle_model])
    end
  end

  def by_model
    @auto_parts = AutoPart.where(vehicle_model: params[:vehicle_model])
  end

  # GET /auto_parts
  # GET /auto_parts.json
  def index
    @auto_parts = AutoPart.all.order(:price)
  end

  # GET /auto_parts/1
  # GET /auto_parts/1.json
  def show
  end

  # GET /auto_parts/new
  def new
    @auto_part = AutoPart.new
  end

  # GET /auto_parts/1/edit
  def edit
  end

  # POST /auto_parts
  # POST /auto_parts.json
  def create
    @auto_part = AutoPart.new(auto_part_params)

    respond_to do |format|
      if @auto_part.save
        format.html { redirect_to @auto_part, notice: 'Auto part was successfully created.' }
        format.json { render :show, status: :created, location: @auto_part }
      else
        format.html { render :new }
        format.json { render json: @auto_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auto_parts/1
  # PATCH/PUT /auto_parts/1.json
  def update
    respond_to do |format|
      if @auto_part.update(auto_part_params)
        format.html { redirect_to @auto_part, notice: 'Auto part was successfully updated.' }
        format.json { render :show, status: :ok, location: @auto_part }
      else
        format.html { render :edit }
        format.json { render json: @auto_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auto_parts/1
  # DELETE /auto_parts/1.json
  def destroy
    @auto_part.destroy
    respond_to do |format|
      format.html { redirect_to auto_parts_url, notice: 'Auto part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auto_part
      @auto_part = AutoPart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auto_part_params
      params.require(:auto_part).permit(:name, :description, :price, :vehicle_make, :vehicle_model)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auto_parts_helper.rb
module AutoPartsHelper
end

app/views/auto_parts/_form.html.erb
<%= form_for(@auto_part) do |f| %>
  <% if @auto_part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auto_part.errors.count, "error") %> prohibited this auto_part from being saved:</h2>

      <ul>
      <% @auto_part.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :vehicle_make %><br>
    <%= f.text_field :vehicle_make %>
  </div>
  <div class="field">
    <%= f.label :vehicle_model %><br>
    <%= f.text_field :vehicle_model %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/auto_parts/by_make.html.erb
<h1>Listing auto_parts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Vehicle make</th>
      <th>Vehicle model</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auto_parts.order('price').last(4).each do |auto_part| %>
      <tr>
        <td><%= auto_part.name %></td>
        <td><%= auto_part.description %></td>
        <td><%= auto_part.price %></td>
        <td><%= auto_part.vehicle_make %></td>
        <td><%= auto_part.vehicle_model %></td>
        <td><%= link_to 'Show', auto_part %></td>
        <td><%= link_to 'Edit', edit_auto_part_path(auto_part) %></td>
        <td><%= link_to 'Destroy', auto_part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Auto part', new_auto_part_path %>

app/views/auto_parts/by_model.html.erb
<h1>Listing auto_parts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Vehicle make</th>
      <th>Vehicle model</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auto_parts.order('price').each do |auto_part| %>
      <tr>
        <td><%= auto_part.name %></td>
        <td><%= auto_part.description %></td>
        <td><%= auto_part.price %></td>
        <td><%= auto_part.vehicle_make %></td>
        <td><%= auto_part.vehicle_model %></td>
        <td><%= link_to 'Show', auto_part %></td>
        <td><%= link_to 'Edit', edit_auto_part_path(auto_part) %></td>
        <td><%= link_to 'Destroy', auto_part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Auto part', new_auto_part_path %>

app/views/auto_parts/by_price.html.erb
<h1>Listing auto_parts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Vehicle make</th>
      <th>Vehicle model</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auto_parts.order('price').each do |auto_part| %>
      <tr>
        <td><%= auto_part.name %></td>
        <td><%= auto_part.description %></td>
        <td><%= auto_part.price %></td>
        <td><%= auto_part.vehicle_make %></td>
        <td><%= auto_part.vehicle_model %></td>
        <td><%= link_to 'Show', auto_part %></td>
        <td><%= link_to 'Edit', edit_auto_part_path(auto_part) %></td>
        <td><%= link_to 'Destroy', auto_part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Auto part', new_auto_part_path %>

app/views/auto_parts/edit.html.erb
<h1>Editing auto_part</h1>

<%= render 'form' %>

<%= link_to 'Show', @auto_part %> |
<%= link_to 'Back', auto_parts_path %>

app/views/auto_parts/index.html.erb
<h1>Listing auto_parts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Vehicle make</th>
      <th>Vehicle model</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auto_parts.order('price').last(4).each do |auto_part| %>
      <tr>
        <td><%= auto_part.name %></td> 
        <td><%= auto_part.description %></td>
        <td><%= auto_part.price %></td>
        <td><%= auto_part.vehicle_make %></td>
        <td><%= auto_part.vehicle_model %></td>
        <td><%= link_to 'Show', auto_part %></td>
        <td><%= link_to 'Edit', edit_auto_part_path(auto_part) %></td>
        <td><%= link_to 'Destroy', auto_part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Auto part', new_auto_part_path %>

app/views/auto_parts/new.html.erb
<h1>New auto_part</h1>

<%= render 'form' %>

<%= link_to 'Back', auto_parts_path %>

app/views/auto_parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @auto_part.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @auto_part.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @auto_part.price %>
</p>

<p>
  <strong>Vehicle make:</strong>
  <%= @auto_part.vehicle_make %>
</p>

<p>
  <strong>Vehicle model:</strong>
  <%= @auto_part.vehicle_model %>
</p>

<%= link_to 'Edit', edit_auto_part_path(@auto_part) %> |
<%= link_to 'Back', auto_parts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AutopartsStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>